name: Test MNIST Model

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest matplotlib numpy==1.26.0 tqdm
        
    - name: Run tests
      run: |
        python -m pytest test_model.py
        python train.py
